{{- if eq .Values.environment "dev" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.fullname }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  EXTERNAL_INTGERATION_KEY: c2VjcmV0X3ZhbHVlX2Rldg==
{{- end }}