apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.data.fullname }}
  annotations:
  {{- with .Values.annotations }}
     {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.data.fullname }}
  {{- if eq .Values.environment "prod" }}
  {{- toYaml .Values.data.autoscaling.prod | nindent 2 }}
  {{- else if eq .Values.environment "dev" }}
  {{- toYaml .Values.data.autoscaling.dev | nindent 2 }}
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.data.autoscaling.cpuTh }}