---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.data.fullname }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: {{ .Values.data.fullname }}
